version: "3.9"

services:

  fastapi:
    build: ./api
    container_name: timefastapi
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: timenginx
    ports:
      - "8201:80"
    depends_on:
      - fastapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
